# -*- coding: utf-8 -*-
"""Language_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17J5OdgTCiSQLEyqe29fyLUtaiRpJLErW
"""

pip install langdetect

from langdetect import detect
detect('Good Morning, How are you?')

from langdetect import detect
detect('காலை வணக்கம் எப்படி இருக்கிறீர்கள்?')